### ISSUE TITLE
Can this work from my theme to update multiple plugins?

### ISSUE THREAD

**Issue by ryanlabelle** [YahnisElsts/plugin-update-checker#101]
Very useful script, thank you. 

Just wondering if I can use this in my theme to update / check multiple plugins hosted on github. I'd like to have one copy of the script in my theme directory and set it up to check multiple plugins I use to support the theme. Seems like I would need one copy for each plugin I host. Is that the case?

Thanks so much. 

I also use TGM plugin activator which is great for the initial download but does not check for updated versions.

**Comment by YahnisElsts** [comment]
You only need one copy of the script. You can create multiple instances of the update checker class without making multiple copies of the actual files.

For example, you could do something like this:

```php
require 'plugin-update-checker/plugin-update-checker.php';
$firstUpdateChecker = Puc_v4_Factory::buildUpdateChecker(
	'https://github.com/user-name/repo-name-1/',
	'/full/path/to/plugin-1',
	'plugin-1-slug'
);

$secondUpdateChecker = Puc_v4_Factory::buildUpdateChecker(
	'https://github.com/user-name/repo-name-2/',
	'/full/path/to/plugin-2',
	'plugin-2-slug'
);
```

Alternatively, you could keep the update checker library in the theme but place the actual initialization code in each plugin. That could be easier since you could use the `__FILE__` constant instead of trying to figure out the full path to each plugin.

**Comment by ryanlabelle** [comment]
Thank you sir! Works great!
