### ISSUE TITLE
PUC debug bar output hidden since WP Debug v0.9

### ISSUE THREAD

**Issue by robertharm** [YahnisElsts/plugin-update-checker#102]
Hi Yahnis,

thanks for the continued support of the plugin updater, which we are using in our plugins.

I updated from v2.2 to v4.1 this weekend & it works fine so far. Anyway I now also updated the plugin Debug bar to v0.9 and as a result, the content is not visible anymore. As you can see from the following screenshot, the related div has the property display:none. If I remove them in the console, the content is visible again:
![pub-debug-bar-issue](https://cloud.githubusercontent.com/assets/158669/26118585/c8f24c92-3a6a-11e7-99fe-1e7482bf740f.png)

If I switch back to WP Debug v0.8.4, this issue is gone.
 
Any ideas how to fix this? I will also open a related ticket on the WP Debug support forum...
best,

Robert

**Comment by YahnisElsts** [comment]
Thank you for the report. This should be fixed in 235a810.

While trying to reproduce the problem, I noticed a related issue: when there are multiple instances of the update checker (all from the same version of the library), only one of them shows up in the admin bar drop-down menu that was introduced in Debug Bar 0.9. It's because Debug Bar incorrectly assumes that every debug panel corresponds to a unique PHP class. There don't seem to be any filters or other ways to override that. AFAIK, there's no practical way to create new classes on the fly (unless you're using PHP 7), so that's that.

**Comment by robertharm** [comment]
Thanks - this fixed the issue!
