### ISSUE TITLE
Show details of plugin hosted on GitHub

### ISSUE THREAD

**Issue by italoiz** [YahnisElsts/plugin-update-checker#103]
Is it possible to display details of the plugin that is hosted on GitHub? Even though it is already up to date. Using the readme.txt that is there, or otherwise.

What are the ways I can do this?
Can I contribute to the project?

**Comment by YahnisElsts** [comment]
How exactly do you want to display these details? I'm reluctant to add stuff to the default WordPress UI, but if you want to show something on your plugin page (for example), I would be willing to add some hooks or API functions to help with that.

There's almost certainly a way to display the standard plugin information pop-up even for a plugin that's up to date, but I'd have to examine the core code to know for sure.

**Comment by iiandrade** [comment]
View as when we click to see details of the new version when an update is available. This would be ideal as well as the plugins that are hosted in the official WordPress repository.

Like this:
![hostedplugin](https://cloud.githubusercontent.com/assets/8454560/26256709/31b75cba-3c94-11e7-8f41-906f956de0c9.png)

But it would be interesting to display the FAQ tab that we can put in readme.txt.

**Comment by YahnisElsts** [comment]
I've done a bit of research. Here's a working example of how to make a link like that:

```php
add_action('admin_init', function () {
	wp_enqueue_script('plugin-install');
	add_thickbox();
});

add_action('admin_notices', function () {
	$infoUrl = add_query_arg(
		array(
			'tab' => 'plugin-information',
			'plugin' => 'akismet',
			'section' => 'changelog',
			//Thickbox parameters
			'TB_iframe' => 'true',
			'width' => 772,
			'height' => 895
		),
		admin_url('plugin-install.php')
	);

	$detailsLink = sprintf(
		'<a href="%1$s" class="thickbox open-plugin-details-modal">View plugin details<a>',
		esc_url($infoUrl)
	);

	echo '<div class="notice notice-info"><p>', $detailsLink, '</p></div>';
});
```

**Comment by iiandrade** [comment]
I will try to do this implementation here. I will also try to pull a request if it works, and I see it useful to other people.

Thank you!

**Comment by YahnisElsts** [comment]
Before you make a pull request, please consider posting more details about where you plan to place this link and if/how it's going to change the update checkecr API (e.g. new public methods, etc). It'll improve the chances that your pull request is accepted and it might save you some work 😄

**Comment by iiandrade** [comment]
No problem!

I'll post it here, so you can see all the requests and modifications that will occur, including I'm already doing, and I'm having a good result.

Thank you!

**Comment by iiandrade** [comment]
To be able to make the changes I needed, and a few more, to meet my needs, which may also serve other people.

I'll tell you a little about what I've changed!

* The first thing I changed was, add a "View Details" link next to the "Check for Updates" link, so it will work as if it were a normal plugin, showing the details that is in the `readme.txt` of the last one version. I also put a condition for there are no duplicates of the same link, since when you have an update available, the "View details" link appears, I believe it is the WordPress itself that places. See the image below:

![a3349](https://cloud.githubusercontent.com/assets/8454560/26279469/72169238-3d8b-11e7-9c47-aa6d825f71df.png)

* Another thing I've changed, which in my opinion, I believe will help others, is to allow other types of sections in the `readme.txt` file as a `== Custom Section ==`.

### How did I make this change?
*Simple, I've just applied a filter so other developers can add their own sections. As it is in the form below:*

`apply_filters('puc_readme_section_allowed' ... );` See here in [code](https://github.com/iiandrade/plugin-update-checker/blob/master/vendor/readme-parser.php#L137).

### Adding custom section.
**In PHP code**
```php
function add_custom_section_puc( $sections ) {
  return array_merge( $sections, array('custom_section'));
}
```

**In readme.txt**
```txt
== Custom Section ==

Describe the section here.
```

### Result
![image3344](https://cloud.githubusercontent.com/assets/8454560/26279608/c762b0fc-3d8e-11e7-8aaf-0d2556840140.png)

Once again, sorry for my English.

**Comment by YahnisElsts** [comment]
I'm still reviewing the PR, but here's some further info. It looks like there's another way to make WP itself display the "View details" link: give the core the slug. This indirectly makes it think that the plugin is hosted on wordpress.org, which means that the plugin information API is available, so the core shows the link.

There are several ways to do this. Here's one:
```php
//Example code. Place it in Puc_v4p1_Plugin_UpdateChecker::installHooks()
add_filter('all_plugins', function($plugins) {
	if (isset($plugins[$this->pluginFile])) {
		$plugins[$this->pluginFile]['slug'] = $this->slug;
	}
	return $plugins;
});
```

Side-effect: WordPress will no longer show the "Visit plugin site" link, only "View details". You can't have both links if you're using this approach. 

There's also a risk of other, less obvious side-effects. As far as I can tell, WordPress doesn't explicitly check if a plugin is in the official plugin directory. Instead, it relies on indirect indicators like "does the update response for this plugin include a 'slug' field?". Jetpack does the same thing. 

It's an interesting alternative that takes significantly less code, but I'm not sure if it's worth the risk that it could introduce new bugs and unexpected interactions.

**Comment by YahnisElsts** [comment]
I'm closing this issue because it has been inactive for a couple of years and the referenced PR has been closed for a while.
