### ISSUE TITLE
Only display notification for update available

### ISSUE THREAD

**Issue by rinkuyadav999** [YahnisElsts/plugin-update-checker#107]
Hi

I was testing plugin-update-checker but there is a issue. When i move code in main plugin file, then it displays update notification and link to update plugin and also link next to plugin 'check for update' BUT when i move code in other file and include this file in main plugin file, then it display only notification in Plugin menu and under Dashboard > Update but it does not display link to update plugin and also link next to plugin 'check for update'.

Seems this library does not include some files when i move code in other file and require it in main file.

Something like:

`
    define( 'MYPLUGIN_ABSPATH', plugin_dir_path( __FILE__ ) );
    require MYPLUGIN_ABSPATH . 'inc/checkupdate.php';
`

And code which check for update are in checkupdate.php like

`
    require MYPLUGIN_ABSPATH . 'inc/plugin-update-checker/plugin-update-checker.php';
	$myUpdateChecker = Puc_v4_Factory::buildUpdateChecker(
		'http://localhost/work/json/info.json',
		__FILE__,
		'myplugin'
	);
`

your help will be highly appreciated

Thanks

**Comment by YahnisElsts** [comment]
The second argument to the `buildUpdateChecker()` method must be the full path of the main plugin file. The problem is that the your code still uses the `__FILE__` constant which contains the full path of the *current* file (i.e. `checkupdate.php`), not the main file. Replace it with the full path and file name of the plugin file.

Personally, I would do it like this. Define a constant in the main plugin file:

```php
define('MYPLUGIN_PLUGIN_FILE', __FILE__);
```

Then use it in `checkupdate.php`:
```php
require MYPLUGIN_ABSPATH . 'inc/plugin-update-checker/plugin-update-checker.php';
$myUpdateChecker = Puc_v4_Factory::buildUpdateChecker(
    'http://localhost/work/json/info.json', 
    MYPLUGIN_PLUGIN_FILE, 
    'myplugin' 
);
```
