### ISSUE TITLE
Can't get changelog details from readme.txt

### ISSUE THREAD

**Issue by jlethuau** [YahnisElsts/plugin-update-checker#114]
Hi,
first of all, thanks for this great and very useful plugin.
I'ts really simple and its documentation is really good!

I use this updater to manage release of my plugins (hosted on bitbucket private reposirories) and everything is OK when I make releases, except the Changelog tab :(

My readme.txt is really simple and has a proper Changelog section but when I Click on the "show version details" tab, there in no content in it.

Is this something particular to do? I've seen there are other ways to deal with changelog but this one (with readme.txt) is simpler.

Thanks for your help!

**Comment by YahnisElsts** [comment]
Try validating the readme.txt with the [Readme Validator](https://wordpress.org/plugins/developers/readme-validator/). Does it show any errors regarding the changelog section?

Also, could you post the contents of the readme? If you don't want to make it public, you can email it to me: `whiteshadow@w-shadow.com`

**Comment by media-store-net** [comment]
Hi, i have the same problem with a private Repo.
In debug bar I get a failure by Request Info.
If I make this Repo as free, Request Info is OK.
I've added a consumer to my account and sets the key and secret.
What's about the Callback URL in the consumer settings? This is a required filed in the Docs of Bitbucket.
https://confluence.atlassian.com/bitbucket/oauth-on-bitbucket-cloud-238027431.html#OAuthonBitbucketCloud-OAuth2.0
What i do wrong?

**Comment by jlethuau** [comment]
Hi,
sorry for the late reply but finally, it's OK for me.
I don't know exactly what was going wrong in my first tries...
Possible reasons:

- renaming README.txt for readme.txt (case sensitive)
- encoding issue?
- added FAQ section 
- some cache issue???

**Comment by YahnisElsts** [comment]
@jlethuau 
I believe that file names *are* case-sensitive as far as Git & BitBucket are concerned. Most likely, that's what the problem was.

@media-store-net 
Make sure that your repository URL is correct. It should look similar to this:
`https://bitbucket.org/UserName/repository-name`

Note that the protocol is `https` and there's no trailing slash. Also, double-check the `consumer_key` and `consumer_secret` values. 

> What's about the Callback URL in the consumer settings? This is a required filed in the Docs of Bitbucket.
https://confluence.atlassian.com/bitbucket/oauth-on-bitbucket-cloud-238027431.html#OAuthonBitbucketCloud-OAuth2.0

I don't know that much about OAuth, but the current implementation (without a callback URL) seems to work fine in practice. I tested it less than 5 minutes ago.

**Comment by media-store-net** [comment]
Work fine for me now.
The URL was it.
Many Thanks... I like it, Good Job

**Comment by YahnisElsts** [comment]
All right, that's good to hear. I think this issue has been resolved.
