### ISSUE TITLE
Symbolic links during development not supported

### ISSUE THREAD

**Issue by mwawrusch** [YahnisElsts/plugin-update-checker#142]
I am trying to streamline our development environment and use symbolic links to link from the plugin directory into the plugin source
```
cd .../wp-content/plugins
ln -s /Users/..../my-plugin-src my-plugin
```
This breaks in line 50 of the v4 factory as it can't determine if this is a plugin or a theme.

So an easy solution would be to just print out a warning that the autoupdate is not active. It does not need to be running during dev anyways.

**Comment by YahnisElsts** [comment]
I think this was already reported in #82, but the original reporter never got back to me about the suggested fix.

In theory, the update checker is supposed to work around the symlink problem by examining the file header. This happens in the second half of the `Puc_v4_Factory::isPluginFile()` method, around line 153. Any idea why that doesn't work in your case?

> So an easy solution would be to just print out a warning that the autoupdate is not active. It does not need to be running during dev anyways.

I don't think a warning is sufficient in this case. There are other ways the "plugin or theme?" check could go wrong, like if someone passes in an incorrect file name. If that happens, you want the code to fail immediately and loudly so that the person responsible can find and fix the bug.

**Comment by mwawrusch** [comment]
We are using the wordpress plugin boilerplate where we the actual plugin code is in include/... - there was no "Plugin Name" there so the updater did not find it. We added it and now it works. Not the cleanest solution but good enough.

**Comment by YahnisElsts** [comment]
That doesn't sound right. You wouldn't even be able to activate the plugin if it didn't have that header. Are you using [this WordPress plugin boilerplate project](https://github.com/DevinVinson/WordPress-Plugin-Boilerplate)? It *does* have a standard plugin header which includes `Plugin Name` among other things.

Please double-check that you're passing the correct file name to `buildUpdateChecker`. It must point to the file that contains the plugin header, not some other file in some subdirectory.

**Comment by YahnisElsts** [comment]
I'm closing this issue because it has been inactive for more than a year.

If you still encounter this problem, feel free to reopen the issue or create a new one.
