### ISSUE TITLE
4-5 HTTP API requests when checking for updates. Is that normal?

### ISSUE THREAD

**Issue by claytoncollie** [YahnisElsts/plugin-update-checker#148]
I am hosting a private repo on BitBucket.  Updates work fine, but when looking at Query Monitor, I am seeing 4-5 HTTP requests.  With one plugin that is fine, I guess, but those requests can add up and slow down the admin section with more plugins checking for updates.  Is that normal to have 4-5 requests when checking for an update?  Why not use the first request to get all of the info you need like the readme.txt file and store it? 

![image](https://user-images.githubusercontent.com/4236538/32193242-ab9256e0-bd84-11e7-81b1-0297d053ad82.png)

![image](https://user-images.githubusercontent.com/4236538/32193247-b3f81310-bd84-11e7-9386-69db33118c1d.png)

![image](https://user-images.githubusercontent.com/4236538/32193264-be3bb9c6-bd84-11e7-83e5-6300fdfee99e.png)

**Comment by YahnisElsts** [comment]
This is normal. It works this way because I want to support several different ways to release updates and specify the latest stable version:

- A `Stable tag` header in readme.txt.
- Tags formatted as version numbers, e.g. `v2.01`.
- A specific stable branch.
- Just using the `master` branch for everything.

The update checker starts by checking the remote readme for the aforementioned header, then tries to find suitable tags, and finally defaults to using the `master` branch as the latest version. 

> Why not use the first request to get all of the info you need like the readme.txt file and store it?

Is there way to do that without locking everyone into one specific release workflow?

**Comment by claytoncollie** [comment]
In a perfect world, I'd like my only method to be tags as it's what I'm just comfortable with.  And since that is the second option after checking the readme.txt, maybe that choice could be set like you can set your branch choice.  I'm just thinking of a way to reduce the number of HTTP API calls.  

`//Optional: Set the branch that contains the stable release.
$myUpdateChecker->setBranch('stable-branch-name');`

`//Optional: Set your preferred method to check for udpates.
$myUpdateChecker->setMethod('readme');

$myUpdateChecker->setMethod('tags');

$myUpdateChecker->setMethod('stable-branch');`

**Comment by YahnisElsts** [comment]
> In a perfect world, I'd like my only method to be tags as it's what I'm just comfortable with

You can do that by overriding the `chooseReference()` method in the VCS API class. Here's an example:

```php
class CustomBitBucketApi extends Puc_v4p3_Vcs_BitBucketApi {
	public function chooseReference($configBranch) {
		//Use only tags.
		return $this->getLatestTag();
	}
}

//Create an update checker instance directly instead of using the factory.
$updateChecker = new Puc_v4p3_Vcs_PluginUpdateChecker(
	//Pass in an instance of your custom API client as the first argument.
	new CustomBitBucketApi('https://repository-url-here'),
	//All other arguments are the same as for buildUpdateChecker().
	__FILE__,
	'my-plugin-slug'
);
```

For comparison, take a look at the [default implementation of `chooseReference()`](https://github.com/YahnisElsts/plugin-update-checker/blob/22fd23a32b158ac051f09690c757f5fe509d21aa/Puc/v4p3/Vcs/BitBucketApi.php#L38).

**Comment by claytoncollie** [comment]
This worked like a charm! Thank you for the assistance.  I've reduced the HTTP calls significantly.  I am now getting 3 calls per plugin when using tags.  Any ideas on how to get these does to 2 or even 1?

![image](https://user-images.githubusercontent.com/4236538/32572954-f1578ca4-c491-11e7-8568-0eeb44286bbf.png)

**Comment by YahnisElsts** [comment]
I don't think there's any way to reduce it to 1 request. You need to know what the latest tag is before you can get update information from that tag. This means you *must* make at least 2 requests: one to get a list of tags, then at least one more to retrieve something from a specific tag.

As for actually getting it down to 2 requests, I don't think BitBucket API offers a way to retrieve multiple files with one request. So unless you get rid of `readme.txt`, it has to be 3 requests: 
1. Get tags.
2. Get the plugin file.
3. Get the readme.

If the number of requests is very important to you, maybe you'd be willing to use the JSON metadata option instead of BitBucket integration? It takes more work to set up and maintain, but all of the update information can be retrieved with a single HTTP request.

Also, keep in mind that normally the library only checks for updates twice per day (or once per hour on certain admin pages like "Dashboard -> Updates"). Maybe it won't add up to all that much?
