### ISSUE TITLE
Can I use this to update a forked version of a free plugin?

### ISSUE THREAD

**Issue by planetahuevo** [YahnisElsts/plugin-update-checker#149]
Hi,
I am using a forked version of a free plugin. I have modified the code of the free plugin to adapt it to my needs. 
When a new update is on the free repo, I download it, merge it (or adapt it again if the changes are big) with my custom code and upload it manually to my 6 sites. 
I would like to be able to update the plugin with my bitbucket, but I am not sure how this will clash with the  update notification from the free official repo. 
Will this work? 
Is there anything I should do to make this work? 
I prefer not to change the slug, as this will affect the original plugin (translations, etc). 
Thank you very much!

**Comment by YahnisElsts** [comment]
Yes, I think that would work. The update checker will automatically overwrite updates from other sources. You don't need to do anything special to enable that.

The only catch that I know of is that this only works while your plugin is active. This is because the update checker is part of the plugin code. It can't do anything if the plugin isn't loaded. So if the user deactivates the plugin, an update from wordpress.org might show up.

**Comment by planetahuevo** [comment]
Fantastic news! You are going to save me a loooot of time on my workflow. 
I am going to install this today. 
I use the fantastic "hide plugins" to avoid other admin users to click on the wrong buttons.
https://wordpress.org/plugins/hide-plugins/
In case it helps others with the same issues. 
 👍 
I will let you know how it goes.
Thank you!
