### ISSUE TITLE
Credentials check and/vs silent fail

### ISSUE THREAD

**Issue by berengerzyla** [YahnisElsts/plugin-update-checker#151]
Hi!

This is more of an improvement than a real bug.
I am using this great lib (shout to everyone who made it possible, btw) to offer updates to a private plugin.
My plugin is hosted on a private GitLab, and for that, I tweaked my plugin to mix PUC and a credentials box ([http://open-tools.net/documentation/tutorial-automatic-updates.html#wordpress](http://open-tools.net/documentation/tutorial-automatic-updates.html#wordpress) / mentionned somewhere here). Works like a charm, with a couple of "but".

- I know it would extend the system quite a bit (without interfering too much with the core of PUC), but how would you feel to integrate a system like the credentials holder directly into PUC?

- Also, there is something a bit odd, in the way that if credentials are incorrect, or missing, checking for an update will return "Plugin is up to date". The API call will actually return a 404 (Project missing or so).
If credentials are set upon PUC construction, it would be good to check them properly.
For instance: `/api/v4/projects/user%2Fproject/?private_token=WRONG_TOKEN` will return `HTTP/1.1 401 Unauthorized`, which we could handle.
An oddity is that `/api/v4/projects/user%2Fproject/?private_token=` (empty / not set in the code or admin) will return `HTTP/1.1 404 Not Found`.
But since we are the content creators (plugin/theme writers), we know in advance that if the token is empty, then it's incorrect.
Question here is, could we implement over PUC some authentication-verification methods? I'd rather see "Please check the authentication info / Please register", than "Your plugin is up-to-date" when authorization actually fails.
Even having an action (or filter) to catch that would be great.

**Self-hosted**: the authentication verification method wouldn't be provided (as it would depend on the project), but we could provide a hook for that (with a __return_true as a default).
**GitHub/GitLab**: as mentioned above, it could just be to try to connect onto the project via the API.
**BitBucket**: don't know if the API actually offers that?

I could work on it if you think it would be good to have that.

**Comment by Mikk3lRo** [comment]
If I understand this correctly it's about integrating a sort of license key system into PUC...? IMO that is not a good idea - updates and licensing are (almost) completely separate concepts, though I'm aware that many plugins require one for the other.

Add to that the fact that there are tons of different ways to implement a licensing system, so adding code that covers just one way of doing it seems almost counter productive. In fact I already dislike including a bunch of code for update methods other than the one I actually use... I might suggest ways to avoid that if I find time, but that is a separate issue - just making a point about including "specialized code".

Invalid API-credentials, on the other hand, could definitely use some better error-handling - I too was confused by the message that there were no updates - when in fact the API-credentials did not allow the required access (bitbucket private repos in my case). I imagine there are other errors that fail in the same "silent" way. I'm unsure if it's intentional though, as more descriptive errors would be very helpful for us (developers), but I can imagine many cases where it would be undesirable to show the end-user "too much information".

Still, I think "Cannot determine if there are updates available" would probably be better. It would tell an end user that "something" is wrong, so they might contact us - without giving away too much information about *what* we screwed up :)

**Comment by YahnisElsts** [comment]
### UI for Credentials

It would be useful, but, as @Mikk3lRo said, there are lots of different authentication and licensing systems. Sure, for GitHub/GitLab you can just append a few query parameters to the URL. However, BitBucket requires either OAauth or JWT, and self-hosted services can use anything from simple license keys to client logins, authentication headers or even home-grown cryptographic signatures. Also, they might need to display additional information like license type, expiration date, a list of authenticated sites/users, and so on.

I don't think it's realistic to make an implementation that's flexible enough to support most uses cases. And if it's only going to work for a couple of services then it's probably not worth it.

### Error handling

Update checks failing silently was an intentional choice. Long ago, when I originally wrote that part of the code, the only supported update mechanism was downloading a remote JSON file, and there was no "check for updates" link. In that situation, the most likely reason why an update check would fail was that your site was down. The end user has no way to fix that problem and it's probably temporary anyway, so there's no need to confuse them with error messages.

As for developers, enabling `WP_DEBUG` will make PUC trigger a PHP warning when it fails to retrieve the JSON document.

These days there *is* a "Check for updates" link. I agree that it would be better to show an error message when a manual check fails. The problem is that you'd have to somehow pass that error up the stack to `Puc_v4p3_Plugin_UpdateChecker::handleManualCheck()` or even `displayManualCheckResult` (which runs on the *next* page load), and do it in a way that doesn't interfere with other parts of PUC or with user sites. Exceptions, maybe? You'd have to be very careful with where you catch them.

Thoughts?

**Comment by berengerzyla** [comment]
@Mikk3lRo, @YahnisElsts, thank you both for your replies.

# UI
I understand about UI, and it was more of an open question. Since PUC has to be wrapped anyway, the credentials UI can be in that wrapper.

# Error handling
About that, I totally get the history of the project, and I understand the choices.
Exceptions might not be the best as it would be harder to implement them in the core without interering.
But WordPress has filters and actions we can rely on.

One option I could see would be to add `do_action` callers in the `api` method itself whenever you return wp_errors. You create them or pass them along, but they are usually transformed into `null` one level up, before we have any access to them. If, for example, in the `GitLabApi`, the `api()` method were to be …

```
$response = wp_remote_get($url, $options);
if ( is_wp_error($response) ) {
	do_action( 'puc-gitlab-http-error', $response );
	return $response;
}

[…]

do_action( 'puc-gitlab-http-error', $response );
return new WP_Error(
	'puc-gitlab-http-error',
	'GitLab API Error. HTTP status: ' . $code
);
```

… I'd be able to hook onto that and take appropriate action. Is it a network error? Then ok, let's let this one slip through. We have a `500`? I can let my client/user know of something. A `401 Unauthorized` can allow me to tell the user to check the credentials.
If hooked onto, those actions would allow more flexibility and response, in manual check or in the automated ones (a 401 in an automated could invalidate my credentials and show them to the user later).
If not, for those who don't want them … it does not change a thing. And actions instead of filters because those API calls are too important.

That's one approach.

**Comment by YahnisElsts** [comment]
The above commit introduces a new `puc_api_error` action that you can use to detect and log errors. The hook callback will receive up to 4 arguments:

- `$error` - A WP_Error instance that provides a brief description of the error. This argument is always available.
- `$response` - The value returned by `wp_remote_get()`. Can be omitted if the original response is not available at the point where the error occurred.
- `$url` - The URL that the update checker requested. Can be omitted.
- `$slug` - The plugin or theme slug. Can be omitted for JSON validation errors. 

Very basic usage example:

```php
function my_callback($error, $response = null, $error = null, $slug = null) {
    if ( isset($slug) && ($slug !== 'my-slug') {
        return;
    }   
    //Do something with the error.
}

add_action('puc_api_error', 'my_callback', 10, 4);
$updateChecker->requestUpdate();
remove_action('puc_api_error', 'my_callback', 10);
```

Also, the update checker will now show these errors when you click the "Check for updates" link and PUC can't find any updates.

**Comment by berengerzyla** [comment]
Thank you @YahnisElsts.
I'll go through that and test it in the next days.
I can cover GitLab, GitHub and self-hosted related actions.
Thank you again!
