### ISSUE TITLE
No updates found

### ISSUE THREAD

**Issue by grizgza** [YahnisElsts/plugin-update-checker#154]
I'm migrating from the old theme update checker to PUC. Everything seems to be setup correctly and it seems to be pulling in the new version # correctly from the JSON file.

However, it is reporting no updates available. Even though the current version of the theme is 2.3 and 2.21 is installed. Not sure if I'm missing something.

<img width="1211" alt="screenshot 2017-11-16 15 44 01 copy" src="https://user-images.githubusercontent.com/621500/32914996-728a795e-cae5-11e7-8058-1434728b2f8a.png">

**Comment by YahnisElsts** [comment]
The update checker uses the [`version_compare()`](http://php.net/manual/en/function.version-compare.php) function to compare version numbers. According to that function (and SemVer), 2.21 is greater than 2.3. This is because 21 > 3.

Possible solutions:
- Change 2.21 to 2.2.1.
- Change 2.3 to 2.30. Though there's a small risk that the trailing zero could be truncated by something somewhere.

**Comment by grizgza** [comment]
Got it, had a feeling it had to do with the version numbering. Thanks for the quick response!
