### ISSUE TITLE
( ! ) Notice: Undefined offset: 1 in yahnis-elsts/plugin-update-checker/vendor/readme-parser.php on line 161

### ISSUE THREAD

**Issue by connerbw** [YahnisElsts/plugin-update-checker#164]
Readme currently looks like this:

https://github.com/pressbooks/pressbooks-docraptor/blob/532decde190aae9ad69b6dfe408c79ca7ab43f22/readme.txt

`$split` looks like:
```
Array
(
    [0] => <p>DocRaptor for Pressbooks require Pressbooks &gt;= 4.3.3.</p>
)
```

**Comment by YahnisElsts** [comment]
That's because the "Upgrade Notice" section is expected to follow this format:

```markdown
== Upgrade Notice ==
 
= 1.0 =
Upgrade notices describe the reason a user should upgrade.  No more than 300 characters.
 
= 0.5 =
This version fixes a security related bug.  Upgrade immediately.
```

Basically, it's [the WordPress.org readme format](https://developer.wordpress.org/plugins/wordpress-org/how-your-readme-txt-works/). The readme you posted doesn't have a version number for the upgrade notice. 

I'll change the parser to ignore the "Upgrade Notice" section if it's formatted incorrectly.
