### ISSUE TITLE
Using the same slug as a plugin in the offical repos

### ISSUE THREAD

**Issue by kaleidoscopique** [YahnisElsts/plugin-update-checker#169]
Hey,

My (private) plugin uses the same slug as another plugin, which is in the official WP repos. 

Some users (not all users, that's what is weird) told me my auto-update system downloads the other plugin instead of updating my plugin (the one in the repos with the same slug).

Is it a know bug, is it a normal WP behaviour, is it my fault, is there a way to prevent it from happening? I'm a bit lost.

Thanks!

**Comment by maxviewup** [comment]
Maybe changing the slug? is there an reason to use the same slug? I had this problem forking an plugin and to work i changed te slug

**Comment by YahnisElsts** [comment]
In theory, this update checker should override updates from the official repository. However, there are a few exceptions:

- Is your plugin inactive while the update is being installed? The update checker can't tell WordPress to download an update from a custom URL if its code doesn't run. PUC only works while your plugin is active.
- Is it a Multisite network, and, if so, is your plugin not active on the main site? Only plugins that are active on the main site get to run in the network admin and change how/which updates are installed. This is basically the same problem as above.
- Do the affected users use an external site management tool to install updates? I know that PUC works with ManageWP, but I haven't tested it with MainWP or other services. If one of those services gets updates straight from wordpress.org instead of relying on the existing update mechanisms, it might end up inadvertently ignoring the updates supplied by PUC.

Changing the slug may help, but it's not foolproof. I believe wordpress.org has some ability to identify plugins based on file names, plugin names, possibly even other metadata. You might have to change the entire plugin header.

**Comment by maxviewup** [comment]
If you are extending the plugin, maybe you can:

- add the plugin as an dependency: TGMPA can help
- Include the plugin inside yours: TGMPA can help on this too.

This way, you can keep getting the main plugin updates and extending it in yours.

**Comment by YahnisElsts** [comment]
I'm closing this issue because it has been inactive for more than a year.

If it's still valid, feel free to reopen the issue or create a new one.
