### ISSUE TITLE
Checker is returning 404 now

### ISSUE THREAD

**Issue by peter-mumford** [YahnisElsts/plugin-update-checker#171]
PUC was working, until I made a branch in my repo and merged it into the master. I tagged the master and used the debug bar to check for an update. But then PUC didn't find the release, and it gives me this error:
1) GitHub API error. Base URL: "/repos/:user/:repo/releases/latest", HTTP status code: 404.

Oddly, the Cached Update has the correct tag and download URL: version 0.7 is the new tag that PUC can't get. And the download URL in this object DOES find the zip.
```
Puc_v4p3_Theme_Update Object
(
    [details_url] => https://github.com/fresenius-dux/txakolina
    [slug] => txakolina
    [version] => 0.6.5
    [download_url] => https://api.github.com/repos/fresenius-dux/txakolina/zipball/0.7
    [translations] => Array
        (
        )

)
```

**Comment by YahnisElsts** [comment]
The problem is that `style.css` in the tagged release still has a `Version: 0.6.5` header. Plugin/theme headers have precedence over tag names. Try updating the `Version` header and then tag a new update.

The API error doesn't matter in this case. It just means that the repository doesn't contain any releases, only tags.

**Comment by peter-mumford** [comment]
ah, thanks!
