### ISSUE TITLE
cant update plugin

### ISSUE THREAD

**Issue by AlexPBrin** [YahnisElsts/plugin-update-checker#181]
installed the files, modified according to the readme, i get a notice to update but no update link/button??

**Comment by YahnisElsts** [comment]
Does your update info/metadata include a valid download URL? If not, you will get an update notification but there will be no "update now" link.

**Comment by AlexPBrin** [comment]
yes it does

**Comment by AlexPBrin** [comment]
https://conceptc.ca/updates/bni.zip

**Comment by YahnisElsts** [comment]
Thank you for the link. I see what the problem is now: in `functions.php`, the second argument that's passed to `buildUpdateChecker()` is incorrect. This argument must be the full path to the main plugin file. In this case it's `__FILE__` which resolves to `functions.php`, and that is *not* the main file. The main file is the one that contains the plugin header: `bni_pt.php`.

Suggested fix: Define a new constant in `bni_pt.php` that equals to the full path to that file and then pass that to `buildUpdateChecker` instead.

**Comment by AlexPBrin** [comment]
You DA MAN!
