### ISSUE TITLE
Avoiding library conflicts

### ISSUE THREAD

**Issue by tgelz** [YahnisElsts/plugin-update-checker#183]
Hi, thanks for your great library. We're currently rewriting our plugin, which includes your update checker, and we'd like to avoid as many potential conflicts as possible.

While your library utilizes `class_exists` checks, it doesn't exclude the possibility of another plugin using a different or altered version of your library, potentially creating conflicts if that plugin gets loaded before ours and vice versa.

Do you have an idea how this could be solved? Currently, we're maintaining a slightly altered version with added namespaces, but it just doesn't feel "clean" enough.

**Comment by YahnisElsts** [comment]
The version numbers in class names should prevent conflicts between different versions of the library. For example, you can have versions 4.1 and 4.4 loaded at the same time. 

As for conflicts between altered versions, what do you mean by that? In theory, it should not be necessary to modify the actual library code. If you need some custom functionality, my recommendation is to, instead of altering the library, make a new class that extends the library class. 

Of course, that won't help in situations where *someone else* loads a modified version of the update checker, but I don't think there's much that can be done about that anyway. As far as I know, PHP doesn't have a good way to keep your dependencies private/isolated.

**Comment by tgelz** [comment]
Yeah, someone else modifying the library directly is what I'm afraid of. Considering how many plugins with horrible code are out there, I think it's not unlikely that someone is including PUC and directly modifying how the functions work or what they return, rather than using the filters.

I was just wondering if maybe you had a more elegant idea on how to make sure our plugin loads exactly the version of PUC that we include, but I guess I won't be getting around namespacing it.

**Comment by YahnisElsts** [comment]
Unfortunately, I don't have a more elegant solution. If you ever find one, I would love to hear it; it would be useful for this and other libraries.

**Comment by tgelz** [comment]
Will do; thanks for your input.
