### ISSUE TITLE
Integrate with Software License Manager

### ISSUE THREAD

**Issue by solepixel** [YahnisElsts/plugin-update-checker#195]
I've got this working within my plugin now but would like to do better to hide the Gitlab download URL (and my private API key), so I'd like to move this code out of my plugin and use it on my personal site where the plugin is purchased. Is there a tutorial on possibly integrating with Software License Manager / WooCommerce?

Ideally the plugin has a place to insert a License key, then it checks my personal site first using the license key and the personal site will respond with the details about the update. I think even still, the download URL would still be visible. Any suggestions for plugin authors using license keys?

Plugin reference: https://wordpress.org/plugins/software-license-manager/

**Comment by YahnisElsts** [comment]
I've never used Software License Manager and I only have very limited experience with WooCommerce, so, unfortunately, I don't have a tutorial.

As for suggestions, it's not possible to completely hide the download URL because WordPress needs it to actually download the update. What you could do is use:

- Per-customer links (i.e. with license key).
- Site-specific links.
- Time-limited or single-use links.
- Any combination of the above.

Personally, I use a home-made license management tool together with a slightly modified version of [wp-update-server](https://github.com/YahnisElsts/wp-update-server). When a customer activates their license key, my server generates a random token for that site/key combination. This token can then be used to download updates. This way, if a particular download link gets abused, I can revoke the token without invalidating the whole license. Limited-use links would be even better.

In your case, one possible approach would be to create a proxy of sorts between `wp-update-server` and GitLab. Use PUC to retrieve plugin metadata, cache it somewhere, then create a subclass of `Wpup_UpdateServer` that uses that data instead of ZIP packages. Alternatively, create cron job that periodically uses PUC to download the latest version and place it in `/wp-update-server/packages`. This would probably be simpler. Then override the `checkAuthorization` and `filterMetadata` methods in the update server to handle license keys.

Either way, it's going to take some work, but it seems doable.

**Comment by solepixel** [comment]
Wow! Thanks for all the detail and suggestions! I'll need to process this a bit and come up with the best solution that works for my scenario. I definitely like the idea of tokens associated with a site without invalidating the license key. Thanks for the help!

**Comment by solepixel** [comment]
Ok, so what I ended up doing is stored my Repo URL and Access Key on my own server (where SLM/WooCommerce resides). When I check the validity of a license, I will also send along the Repo credentials. This keeps it out of the plugin code and on my server, allowing me to change the Access key whenever I want. I know it's not a fool-proof plan to prevent people from stealing the plugin, but I feel it serves its purpose until I can come up with something better, like working with `wp-update-server`. Thanks again for the help!
