### ISSUE TITLE
Specify download_url for repo hosted in bitbucket?

### ISSUE THREAD

**Issue by HW-Siew** [YahnisElsts/plugin-update-checker#202]
Hi, I have a wp theme repo in bitbucket. Under the repo i have a /dist folder which holds the lastest zipped version of the wp theme. Is there any way i can specify the download_url to that specific file using the bitbucket approach to update the theme?

**Comment by YahnisElsts** [comment]
There is no built-in way to do that. 

However, it might be possible to do it by creating a subclass of `Puc_v4p4_Vcs_BitBucketApi` and overriding the [`getDownloadUrl`](https://github.com/YahnisElsts/plugin-update-checker/blob/master/Puc/v4p4/Vcs/BitBucketApi.php#L143) method. That's the method that generates the update download URL based on the selected branch or tag.

You would also need to change the way you create an update checker instance. Instead of using the factory, create it directly and pass in an instance of your custom API:

```php
$myUpdateChecker = new Puc_v4p4_Vcs_ThemeUpdateChecker(
	new MyCustomBitBucketApi('https://bitbucket.org/user-name/repo-name'),
	$themeStylesheetName, //Could be something like basename(__DIR__) or get_stylesheet().
	'unique-theme-slug'
);
```

**Comment by HW-Siew** [comment]
It is working. Thank you very much.

**Comment by HW-Siew** [comment]
Hi thanks for your advice. I had finally figure it out. It was the plugin absolute path to the main plugin header file.
