### ISSUE TITLE
Not working on local host

### ISSUE THREAD

**Issue by keyinora** [YahnisElsts/plugin-update-checker#209]
Hi am I doing something wrong? I have my theme on both a local host and github. I included this in my function.php file:
require '/var/www/html/wp-content/themes/Default_Template-master/plugin-update-checker-4.4/plugin-update-checker.php';
$myUpdateChecker = Puc_v4_Factory::buildUpdateChecker(
	'https://github.com/CaptivationMedia/Default_Template/',
	__FILE__,
	'Default_Template-master'
);
var_dump($theme_base);
//Optional: If you're using a private repository, specify the access token like this:
$myUpdateChecker->setAuthentication('
b*****************************************6');

I also included the plugin folder in my theme folder. Next, I put the theme.json file in my theme file:
{
	"version": "2.6",
	"details_url": "http://localhost.com/Default_Template-master.zip",
	"download_url": "http://localhost.com/Default_Template-master.zip"
}

Finally, I added a new release. However, the update is not showing in wordpress what am I doing wrong?

**Comment by keyinora** [comment]
Do I need to also include the code and files in my github and not just my local dev?

**Comment by YahnisElsts** [comment]
Try this: install the [Debug Bar](https://wordpress.org/plugins/debug-bar/) plugin and take a look at the "PUC (your-theme-slug)" panel in the debug bar. Does everything look correct there? Click the "Request Info" and "Check Now" buttons and see if they display the correct update information.

You don't need a `theme.json` file when loading updates from GitHub. The update checker will not use that file.

> Do I need to also include the code and files in my github and not just my local dev?

It's not required, though I imagine that you might want to do it eventually just because it's easier to keep all code in one place.

**Comment by YahnisElsts** [comment]
I'm closing this issue because it has been inactive for more than a year.

If you still encounter this problem, feel free to reopen the issue or create a new one.
