### ISSUE TITLE
Question: How to handle self-hosted bitbucket and token credentials

### ISSUE THREAD

**Issue by moritz-orth** [YahnisElsts/plugin-update-checker#217]
Hi there,

I wonder is it possible to add self hosted bitbucket support. Our Version does not allow to use Auth0 but "only" personal access token.

Thanks and regards
Moritz

**Comment by YahnisElsts** [comment]
Personally, I have very little experience with BitBucket and I've never used the self-hosted version. I probably won't have the time to research and implement this any time soon.

If you want to take a shot at adding this feature yourself, I would recommend starting with the [Puc_v4p4_Vcs_BitBucketApi](https://github.com/YahnisElsts/plugin-update-checker/blob/1cb79bcdce541bb77944dd671ac3fd487ca2f3c1/Puc/v4p4/Vcs/BitBucketApi.php) class. You would need to:

- Extend the repository URL parsing in the constructor to support custom URLs.
- Change how the request URL is built in the `api()` method to use the server URL that was passed to the constructor instead of `api.bitbucket.org`.
- Add an [`Authorization` header](https://confluence.atlassian.com/bitbucketserver/personal-access-tokens-939515499.html) with the token (if any) to the [`$options` array](https://github.com/YahnisElsts/plugin-update-checker/blob/1cb79bcdce541bb77944dd671ac3fd487ca2f3c1/Puc/v4p4/Vcs/BitBucketApi.php#L203) that's passed to `wp_remote_get()`.
- Somehow enable authentication for download links. I'm not sure how that works with personal access tokens.

For inspiration, take a look at the [Puc_v4p4_Vcs_GitLabApi](https://github.com/YahnisElsts/plugin-update-checker/blob/1cb79bcdce541bb77944dd671ac3fd487ca2f3c1/Puc/v4p4/Vcs/GitLabApi.php#L5) class. It already supports self-hosted repositories.

**Comment by moritz-orth** [comment]
So far so good, but I cant figure out how to modify the header for the `download_url()` method (that uses `wp_safe_remote_get( $url, $options)`...

Can this be done with `add_filters `or `apply_filters`?

Any Idea?

**Comment by YahnisElsts** [comment]
I think you could use the [`http_request_args`](https://developer.wordpress.org/reference/hooks/http_request_args/) filter for that. It's what PUC uses internally to modify request headers.

One thing to keep in mind is that you probably don't want to modify the header for *all* requests. I would recommend to either a) check the requested URL before making any changes, or b) add your filter just before the request is sent and remove it afterwards. Maybe both.

**Comment by Tofandel** [comment]
There is a small issue, the getVcsService function in the factory does not support adding custom services to it, I'll do a PR to fix this
