### ISSUE TITLE
ThemeUpdater not working in version 4.4

### ISSUE THREAD

**Issue by eelco-4free** [YahnisElsts/plugin-update-checker#224]
When using the ThemeUpdater in combination with self-hosted GitLab, I get the following messages when trying to update a theme:

Renaming wp-newspaper-child-theme-1.0.8-a0f3be4dc18efd1277d9700581ca808ec32150ad to /var/www/vhosts/domain.ext/httpdocs/wp-content/themes/Newspaper-child/functions.php…

Warning: copy(): The first argument to copy() function cannot be a directory in /var/www/vhosts/domain.ext/httpdocs/wp-admin/includes/class-wp-filesystem-direct.php on line 243

Theme update failed.

An error occurred while updating /var/www/vhosts/domain.ext/httpdocs/wp-content/themes/Newspaper-child/functions.php: Unable to rename the update to match the existing directory.

Settings are as followed (it is a private repo):

$myUpdateChecker = new Puc_v4p4_Vcs_ThemeUpdateChecker(
	new Puc_v4p4_Vcs_GitLabApi('self-hosted-git-url'),
	__FILE__,
	'Newspaper-child'
);

I have downgraded to version 4.1 in combination with moving to Bitbucket, and have it working now. But I would like to use 4.4 in combination with selfhosted Gitlab.

**Comment by YahnisElsts** [comment]
For a theme the initialisation code needs to be slightly different. The second argument should be the full path to the theme directory.

Please try replacing `__FILE__` with `dirname(__FILE__)` or `__DIR__`.

**Comment by YahnisElsts** [comment]
@shoeyn That's because PUC will default to the currently active theme  when you set that argument to `null`. This will work most of the time, but it can break if someone creates a child theme from your theme. Then the update checker will switch to showing updates as if they were intended for the child theme.

**Comment by LauraRocks** [comment]
When using the ThemeUpdateChecker, and giving the second argument as "_FILE_", the admin /wp-admin/update-core.php page looks really weird, as it uses the second argument as the "plugin title" so it shows the path to the file as title. And also it loses the version information. Using the "null" as an argument would work but in my case I also need the theme to be child themeable so that won't work either. Any suggestions?

**Comment by YahnisElsts** [comment]
Try replacing `__FILE__` with `basename(dirname(__FILE__))`. If the file that contains the initialisation code is in a subdirectory, you'll need to change the code to get the name of the main theme directory. 

Also, if you're not serving updates from a self-hosted repository, please consider using `Puc_v4_Factory::buildUpdateChecker()` instead. It can handle some of these issues automatically.

**Comment by LauraRocks** [comment]
Thank you very much for the quick response, with that replacement it works like a charm! It's a self-hosted GitLab, so I need to use this one.
