### ISSUE TITLE
Question - handling library updates within plugins?

### ISSUE THREAD

**Issue by erikmolenaarnl** [YahnisElsts/plugin-update-checker#234]
Hi,

Thanks for this great library, it will make updating my custom WP plugins much smoother!

> Download the latest release and copy the plugin-update-checker directory to your plugin or theme.

I was just wondering about this installation line:

**How to handle updates to the library itself?**

Would you recommend I'll replace the directory contents of "plugin-update-checker" with the latest version of your library every time I update my custom WP plugins? What will be 'best practice'?

Thanks again for this great piece of engineering.

**Comment by YahnisElsts** [comment]
Yes, I would recommend just replacing `plugin-update-checker` with the latest stable release. As far as I know, WordPress doesn't really have a mechanism for updating dependencies, so this is what we're stuck with.

If your plugins use multiple libraries, maybe you could use Composer to manage them. Then you could just do `composer update` instead of manually copying and replacing files.

**Comment by erikmolenaarnl** [comment]
Thanks for your kind reply. Composer looks like it is perfect for the job. Thanks!
