### ISSUE TITLE
Updating multiple plugins in Multisite

### ISSUE THREAD

**Issue by zedley** [YahnisElsts/plugin-update-checker#238]
Context: I'm trying update a number of plugins on a multisite instance. Not all of the plugins are network enabled. 

I've read several issues and tried to implement all the fixes I could find:

- Using individual update checkers (including a copy of the library in each plugin and instantiating it there)
- Using a combined approach detailed below

Regardless of what I've tried, updates only work for a theme, not on any of the plugins. When I go in and check Debug Bar, it shows all three plugins and the theme on the left side, but if you click any of the plugin names only the information for the first plugin (alphabetically) shows. The theme works as expected.

Here's the code I'm currently using, on a separate updater plugin that is network activated.

```php
require_once('vendor/plugin-update-checker/plugin-update-checker.php'); 

if ( ! function_exists( 'get_plugins' ) ) {  
    require_once ABSPATH . 'wp-admin/includes/plugin.php';  
}
  
$asert_plugins = array(
    'asert-global-plugin',
    'asert-resources-plugin',
    'asert-updater-plugin'
);

$all_plugins = get_plugins();
foreach($all_plugins as $plugin_slug=>$info) {  
    foreach($asert_plugins as $asert_plugin) if(strstr($plugin_slug,$asert_plugin)) {  
        $var_name = $asert_plugin . '_update_checker';  
        ${$var_name} = \Puc_v4_Factory::buildUpdateChecker(
            'https://bitbucket.org/technicalpenguins/' . $asert_plugin,
            $file = __DIR__ . '/../' . $asert_plugin . '/' . $asert_plugin . '.php',
            $asert_plugin,
            12,
            'bitbucket-'.$asert_plugin
        );
        ${$var_name}->setAuthentication( array(
            'consumer_key'=> 'ACTUAL_KEY',
            'consumer_secret'=> 'ACTUAL_SECRET'
        ));
        ${$var_name}->setBranch('deploy');
    }
}
```

I've tried unique variable names, and even passed a unique option name as the fifth parameter, but I still have the same problems. I'm sure I'm just missing something simple. Any ideas?

**Comment by YahnisElsts** [comment]
I've read through the code sample several times and I don't see anything that could cause the problem that you've described. Of course, it's entirely possible that I'm also missing something simple and obvious.

Some thoughts:

- You mentioned that all of the plugins show up in the Debug Bar, but the contents are the same. Are they *exactly* identical? The list on the left side includes plugins slugs - "PUC (slug-here)" - the debug information also contains a "Slug" field. Are the slugs all the same in the content area, or unique?
- `buildUpdateChecker()` doesn't convert relative file paths to absolute paths. I think this usually wouldn't be a problem, but it might be worth trying to use an absolute path here. Try replacing this line:
    `$file = __DIR__ . '/../' . $asert_plugin . '/' . $asert_plugin . '.php',`
    With something like this:
    `realpath(__DIR__ . '/../' . $asert_plugin . '/' . $asert_plugin . '.php'),`
- Instead of creating update checker instances, try just dumping or logging all of the variables that you would pass to `buildUpdateChecker()`. Does the output match what you expected?

**Comment by zedley** [comment]
Shit, well that's entirely on me. 

I somehow only grabbed the PHP files for this one (subfolder PUC) — and everything is so well-crafted, it appears to work. But, as the debug-bar JS isn't loaded, debug bar loads the href reference (something like #puc_debug-bar-panel), which is always the first plugin alphabetically. Once I ACTUALLY INCLUDED ALL THE FILES, it works perfectly. Sorry about that.

Moral of the story: Always. Use. Composer.
