### ISSUE TITLE
gzinflate data error

### ISSUE THREAD

**Issue by robertharm** [YahnisElsts/plugin-update-checker#27]
Hi Yahnis,

since a while I keep on getting the attached error - happens once after login and then it is gone; have you experienced this one before? 

WARNING: wp-includes/class-http.php:2108 - gzinflate(): data error
do_action('admin_init'), call_user_func_array, PluginUpdateChecker_1_6->maybeCheckForUpdates, PluginUpdateChecker_1_6->checkForUpdates, PluginUpdateChecker_1_6->requestUpdate, PluginUpdateChecker_1_6->requestInfo, wp_remote_get, WP_Http->get, WP_Http->request, WP_Http->_dispatch_request, WP_Http_Curl->request, WP_Http_Encoding::decompress, gzinflate

There is a related WP core trac ticket at https://core.trac.wordpress.org/ticket/22952 - anyway I am not sure if this is caused by my server configuration & your library. Just wanted you to know - if it is not related, please close this issue.
thx,

Robert

**Comment by YahnisElsts** [comment]
I haven't encountered that error myself, but based on the discussion in the ticket you mentioned, it sounds like it's caused by an obscure bug in the WordPress core. The error occurs deep inside the HTTP API. It's probably not related to the update checker as such.

I guess you might be able to work around it by turning off gzip encoding on the server that host update metadata.

**Comment by YahnisElsts** [comment]
I'm closing this issue because it has been inactive for about 4 years. 

If you still encounter this error, feel free to reopen the issue or create a new one.
