### ISSUE TITLE
Is there a way to force an update even if the version numbers match?

### ISSUE THREAD

**Issue by chrisblakley** [YahnisElsts/plugin-update-checker#277]
I'm trying to implement this myself with a series of `resetUpdateState()`, `checkForUpdates()`, and `injectUpdate()`, but something isn't working... I may be fighting the cache still, or maybe something else.

Rarely, but sometimes my remote version JSON file will not get "touched" and I'll end up committing with the exact same version as prior. When this happens, I'd like a way to force a theme update. I can handle the interface and everything fine, but I'm struggling to get PUC to allow the update (or even trick it into thinking the version numbers are different).

Appreciate any ideas, thanks.

**Comment by YahnisElsts** [comment]
That's going to be difficult since it's the opposite of what PUC is designed to do. Still, you might be able to do it by writing your own implementation of `getUpdate()` that skips the version number comparison. Take a look at the current implementations in `Puc_v4p5_UpdateChecker` - it's a very short method.

I'm not sure how WordPress itself handles updates that have the same version number, but I think they were allowed.

**Comment by chrisblakley** [comment]
Thanks for the tip, I'll continue to look into it.

My other thought was to modify the JSON file of the local theme to *reduce* it, then trigger PUC to check for an update. Am I correct thinking that `resetUpdateState()` clears the cached data enough to do another check? Do I need to modify the "schedule" as well so that I can check again right away (and if so is there a recommended way to do so)? Thanks again.

**Comment by YahnisElsts** [comment]
Yes, `resetUpdateState()` will clear the cached update information and reset the "last checked on" timestamp. This will typically make PUC check for updates *soon*, but maybe not immediately. If you want to check right away, call `checkForUpdates()`.

**Comment by chrisblakley** [comment]
I found a way to do this if we could place another filter hook within PUC. With this hook, it's actually pretty easy– WordPress gave me no problems when testing it out.

**Comment by YahnisElsts** [comment]
That workaround seems inelegant to me: it's an indirect solution, and it relies on implementation details (PUC calling `getInstalledVersion()` before returning an update). It works, and you're free to use it in your themes, but I'm not going to add that hook for this purpose.

**Comment by chrisblakley** [comment]
Fair enough. I found a way to do this manually by forcing a manual array into the WordPress update list (outside of PUC). For anyone else who stumbles upon this, here's how I did it:

```php
add_filter('site_transient_update_themes', function(){
	if ( current_user_can('update_themes') && is_child_theme() && $this->is_nebula() && isset($_GET['force_nebula_theme_update']) ){
		$parent_theme = wp_get_theme()->get('Template'); //"Nebula-master" in my case

		$updates->response[$parent_theme] = array(
			'theme' => $parent_theme,
			'new_version' => $this->version('full'), //Does not need to be larger than current version. Should be something like "4.5.6" or whatever
			'url' => 'https://github.com/chrisblakley/Nebula/commits/master',
			'package' => 'https://github.com/chrisblakley/Nebula/archive/master.zip'
		);
	}

	return $updates;
}, 99, 1);
```

One interesting note that may be useful in general is that the `new_version` number does not need to be larger than the current version number (in fact, it can even be lower).

This may not work for everyone- especially if needing something more dynamic, but this did the trick for me. Thanks for the tips- feel free to close this issue.

**Comment by YahnisElsts** [comment]
One thing to keep in mind is that while this code doesn't use PUC, it might not work as expected if you didn't already have PUC set up. This is because GitHub archives use directory names like "repository-branch" (e.g. "Nebula-master") or "repository-commit", but WordPress core expects the directory name to exactly match the theme slug. If PUC is active and configured for the current theme then it will automatically fix the directory name when WordPress installs the update. However, if you're not using PUC at all, update installation will usually fail due to the name mismatch. You would need to either supply a custom ZIP with the correct directory name, or write some code to rename the directory at the right moment.

Anyway, I'll close this now.

**Comment by chrisblakley** [comment]
Interesting- thanks for the info. I was thinking some more last night that this could still be a feature pushed to PUC with a new function that bypasses the update check (and version check) and simply goes right to adding the WP formatted "update" to the list of updates.

That approach could also solve the discrepancy you mentioned too by allowing PUC to correct the mismatch.

**Comment by YahnisElsts** [comment]
It would depend on how exactly it's implemented. I wouldn't want to make permanent changes to the update list because that the list might go out of sync if the plugin/theme is deactivated for some reason or a different version is installed. That's why PUC inserts the update dynamically instead of modifying the `update_themes` and `update_plugins` transients in the database.

**Comment by simplenotezy** [comment]
+1 - I would love this feature as well.

A way to `forceUpdate();` of the plugin. This is needed because WordPress does not allow hosting of premium code in their repository, but with PUC, you could place a button for the user to click, to fetch the "premium" code version.
