### ISSUE TITLE
Automatic background updates for premium themes in Multisite

### ISSUE THREAD

**Issue by NegaSteve** [YahnisElsts/plugin-update-checker#280]
I don't know too much about Wordpress and I was tasked with fixing this for the owner of this website. I have been searching for solutions for hours but can't seem to find one that works.

I am currently trying to add automatic background updates for premum themes to a Wordpress multisite installation that contains multiple sites.

The included sites in the multisite are demos of the premium themes.  The theme updates are in a folder in the server. Each theme has the PUC and is included in the theme's function.php. and they are the active theme in their respective site.

In inspecting the theme in the wp-admin of the respective site, I am able to update the site from there without any problem but I would I would like a way for it to automatically update in the background.

I have tried using this , but it does not seem to work. 
I put this line in a php file in the mu-plugins folder of wp-content.

`add_filter( 'auto_update_theme', '__return_true' );`

Would you happen to know a way to solve this problem?

**Comment by YahnisElsts** [comment]
I'm not very familiar with how automatic background updates work, but could it be that they run in the context of the network admin instead of each individual site? If I remember correctly, when you're in the network admin, WordPress only loads the `functions.php` of the theme that's active on the main site. This means that automatic updates would work for that theme but not for any other themes. You might be able to work around that by putting the update-related code in a mu-plugin or the main site theme so that this code is always active.

**Comment by YahnisElsts** [comment]
I'm closing this issue because it has been inactive for a few months.

If you still encounter this problem, feel free to reopen the issue or create a new one.
