### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined method Puc_v4p5_Plugin_UpdateChecker::setBranch()

### ISSUE THREAD

**Issue by Av1shay** [YahnisElsts/plugin-update-checker#281]
Hey!

For some reason I get fatal error for undefined function by running the following code:
```
require 'plugin-update-checker/plugin-update-checker.php';

$update_checker = Puc_v4_Factory::buildUpdateChecker(
    '***',
    __FILE__,
    'test-plugin',
    1
);

$update_checker->setBranch('master');
```
The class Puc_v4_Factory and all it's dependencies being included in the first line, so I don't see any reason for this fatal error.

**Comment by YahnisElsts** [comment]
I think the error is happening because this update checker only supports a few code hosting services and `git.walkmedev.com` is not one of them. The factory doesn't recognize the domain name, so it assumes that the URL must point to JSON document with update information and it creates an instance of the default update checker class that has no Git support and no `setBranch` method.

Are you trying to point the update checker at a plain Git repository? That's currently not supported. PUC only works with GitHub, BitBucket and GitLab.

However, if it's a private GitLab installation then there is a way to make it work with a few minor changes - let me know if that's what you're trying to do.

**Comment by Av1shay** [comment]
Oh, it's bitbucket self hosted service.
I thought maybe to extend your class to support also this host, you think it's possible in a reasonable amount of time?

**Comment by YahnisElsts** [comment]
I'm not familiar with the self-hosted version of BitBucket. Does it support the same API as bitbucket.org? If the API is the same or very similar, I think it would be relatively easy to modify `Puc_v4p6_Vcs_BitBucketApi` to support it.

**Comment by Av1shay** [comment]
So I was able to make it work using your library and some modifications (mainly changing the API to this one: https://docs.atlassian.com/DAC/rest/stash/3.11.6/stash-rest.html)

Thanks a lot :)
