### ISSUE TITLE
Is there a way trim this library a little?

### ISSUE THREAD

**Issue by otakupahp** [YahnisElsts/plugin-update-checker#343]
I am a kind of  "digital waste freak" and I hate to have code that I won't use, so I wonder if there is a way to remove some unused features depending on the use I will do to the plugin.

For example, I am creating a plugin and I do not need the theme feature, nor the debug bar but I do not know if I can just erase those folders.

**Comment by YahnisElsts** [comment]
It depends. If you want to remove theme support or GitHub/GitLab/BitBucket integration, I think you can indeed just delete the folders. Removing Debug Bar support will take a little more effort because some other library code contains references to those classes. In addition to deleting the folder, you would also need to override the `createDebugBarExtension` method with an empty implementation that does nothing.

However, before you do any of that, I would strongly recommend forking and renaming the library so that your plugin doesn't cause conflicts with other plugins or themes that happen to be using the same version of the update checker and that expect all of the folders to be present. For example, you could globally change the `Puc` class prefix to something like `XyzPuc` and rename the `Puc` subfolder to match.

**Comment by otakupahp** [comment]
You are right! Thanks for the suggestion. I will fork the branch
