### ISSUE TITLE
Add headers when requesting to download plugin from download url?

### ISSUE THREAD

**Issue by hwsiew** [YahnisElsts/plugin-update-checker#362]
Hi, is it possible to add headers when making request to update plugin from the download_url? I am thinking to validate the download_url link for the authenticated user only using the wp-update-server. I managed to validate get_metadata when requesting for plugin metadata using   $updateChecker->addHttpRequestArgFilter($callback). Is there any similar for requesting a download?

Thanks!

**Comment by YahnisElsts** [comment]
This is a tricky one because the download request is not sent by the update checker but by WordPress itself. Personally, I use the [`http_request_args`](https://developer.wordpress.org/reference/hooks/http_request_args/) filter to intercept _all_ HTTP requests and then check if the request URL matches the download URL. To improve performance, you could register your filter in the `upgrader_pre_download` action. This way it will only catch update download requests, not all requests that are ever sent by anyone.

**Comment by hwsiew** [comment]
Great information, Thanks! 

So i guess it will be the same that if the update server response an error for get_metadata or download, the error is not properly display to user for now. It will mistakenly response no new version available. I wouldn't be able to catch the error, format the response and display a notice to user using this update checker right?

**Comment by YahnisElsts** [comment]
Some update checks happen inside cron jobs, so you wouldn't be able to display a notice immediately. Instead, I would recommend storing the error somewhere (like a transient) and then displaying it in a notice later.

You can use one of these filters to intercept the server response: 
- `puc_request_metadata_http_result-$slug` - receives the value returned by `wp_remote_get()`.
- `puc_request_info_result-$slug` - receives a `Puc_v4p9_Plugin_Info` instance or `null`.
- `puc_request_update_result-$slug` - receives a `Puc_v4p9_Update` instance. Doesn't run if there was an error.

**Comment by hwsiew** [comment]
Awesome!! Thanks for the information.
