### ISSUE TITLE
Github integration not working with branches

### ISSUE THREAD

**Issue by erifleit** [YahnisElsts/plugin-update-checker#373]
Hello, I'm trying to do the github integration, I created a repo for my custom theme, and added the following code to my functions.php file: ( I censored some private data )

```
add_filter( 'auto_update_theme', '__return_true' );

require('plugin-update-checker-4.9/plugin-update-checker.php');

$myUpdateChecker = Puc_v4_Factory::buildUpdateChecker(
	'https://github.com/[my-user-name]/[my-branch-name]',
	__FILE__,
	'custom-theme'
);
$myUpdateChecker->setAuthentication('[my-access-token]');
$myUpdateChecker->setBranch('master');
```

I had tested this code with the self hosting options and it worked properly, now using the github solution does not seem to find the updates. I push new versions to the master branch but when checking wordpress debug panel it shows the message: 

```
1) GitHub API error. Base URL: "/repos/:user/:repo/releases/latest", HTTP status code: 404.
Error code:
puc-github-http-error
Requested URL:
https://github.com/[my-user-name]/[my-branch-name]/releases/latest
HTTP status:
404 Not Found
```
So it seems the code is attempting to find a release, but I would like it to simply use the branch feature for this project, as I'm not planning on working using the release feature.

Am I missing something or doing something wrong? Please let me know if you need any more details for this issue.

**Comment by YahnisElsts** [comment]
The fact that PUC looks for releases when the branch is set to `master` is a known issue. Currently, the update checker treats `master` as a special value that indicates that it should try releases and tags first, before looking at the branch. I'll probably change this behaviour in a future update. Technically, it's easy to fix, but I've been putting it off since changing this would break backwards compatibility.

All that said, the update checker should check the `master` branch after it doesn't find any releases. Are you saying that it seems to stop at the error and do nothing more? Or does it still return some kind of plugin information, but that information is incorrect or incomplete? Try the "Request Info" button in the Debug Bar and see what it outputs.

**Comment by erifleit** [comment]
It seems the mistake was on my side. I'm unsure what was causing the issue but I realized I was failing to refresh the version in style.css file properly. Also I switched to a different branch called something different than master. I'm not sure which of the two was the main cause of this issue but it seems to work correctly now. 

Thank you for the quick support! Keep up the great work with this repo, it's incredibly useful!
