### ISSUE TITLE
readme.txt versus readme.md

### ISSUE THREAD

**Issue by claytoncollie** [YahnisElsts/plugin-update-checker#374]
Hi. I searched through the docs and issues to see if there was any info about this but I didn't find anything.

We like the formatting of a markdown file more than a text file. 

Is it possible to use readme.md instead of readme.txt and still have the updater work? 

I was thinking about keeping the readme.txt with only the header and then taking out my instructions and changelog and placing them into the readme.md file. That seems like a good solution but you would lose all of that information being available in the WordPress admin when you click "View version details". Not to mention you would have two readme files.

Thanks for the help!

**Comment by YahnisElsts** [comment]
You don't need to have a `readme.txt` file to use this update checker. However, as you mentioned, if you don't have this file, you'll lose most of the information that's usually shown when you click "View version details" (the version number and update timestamp would still show up, and you can show a changelog by placing it in `changelog.md` or `changes.md`).

Is your `readme.md` [structured like `readme.txt`](https://developer.wordpress.org/plugins/wordpress-org/how-your-readme-txt-works/), or does it use a completely different format/layout? In other words, if you were to rename it to readme.txt, would it be a valid plugin readme as defined by the aforementioned link? If so, it might be relatively straightforward to modify the update checker to look for `readme.md` instead of/in addition to `readme.txt`.

**Comment by claytoncollie** [comment]
That's good to know that we don't need a readme.txt for this script to work. Thank you for the clarification.

After reading the readme.txt specs on wp.org, and looking at other official repos like Gutenberg, I think it is fine to have a readme.txt with general info and also a README.md file. GitHub will pick up the markdown file and display it as the main file on your plugins repo homepage if it is present and fallback to the text file when not.

I do like the other options of having a changelog.md which is really what I am after. 

Thanks for the help.
