### ISSUE TITLE
Inteliphense reports Undefined Method

### ISSUE THREAD

**Issue by SirLouen** [YahnisElsts/plugin-update-checker#410]
When using:

`$my_update_checker->getVcsApi()->enableReleaseAssets();
`

Inteliphense reports:

> Undefined method 'enableReleaseAssets'.

**Comment by YahnisElsts** [comment]
That's because `getVcsApi()` can return several different VCS API subclasses, and only one of them has an `enableReleaseAssets()` method. As long as you're using that class (i.e. the GitHub API), you can probably ignore the warning.

**Comment by SirLouen** [comment]
@YahnisElsts do you know how can I suppress the warning? 
Maybe by calling enableReleaseAssets by referencing the real class instead of calculating it as it does?

**Comment by SirLouen** [comment]
I have not deepened much in the code, but it shall be maybe like this?

`$vcs_api = new Puc_v4p10_Vcs_GitHubApi( $my_update_checker->getVcsApi() );
$vcs_api->enableReleaseAssets();`

**Comment by YahnisElsts** [comment]
No, definitely don't do that. It might get rid of the warning, but that code won't work properly. It looks like it tries to create a new instance of the GitHub API class while passing the original instance as a constructor argument. Most likely, it will just crash or trigger a PHP warning when you try to run it because that's not how you're supposed to initialize the API.

There are different ways to suppress the warning - it depends on what IDE you're using. For example, in PhpStorm I can usually do it like this:
1. Press `Alt + Enter` on the highlighted code to display a context menu.
2. Press `up`/`down` to select the warning.
3. Press `right` to open the warning submenu.
4. Select "Suppress for statement" or another "Suppress..." option.

This will usually add a comment like `/** @noinspection InspectionName */` right before the code. If you know the inspection name, you can probably just add that comment manually instead of going through a bunch of menus.

The process will probably be different in other development environments.

**Comment by SirLouen** [comment]
I think this does the trick:

```php
$vcs_api    = $my_update_checker->getVcsApi();
$new_github = new Puc_v4p10_Vcs_GitHubApi( $vcs_api->getRepositoryUrl() );
$new_github->enableReleaseAssets();
```

**Comment by YahnisElsts** [comment]
That code may run, but I don't think it's what you're looking for since it won't actually make PUC use release assets.

When you initialise PUC with a GitHub repository, it will automatically create an instance of `Puc_v4p10_Vcs_GitHubApi`. That is the object that `getVcsApi()` returns. You can create a new, separate instance of `Puc_v4p10_Vcs_GitHubApi` if you want, but that will have no effect on the update checker. Any changes that you make to your new instance - like calling `enableReleaseAssets()` - will not propagate to the instance used by the update checker.

Unless you have a good reason to manually set up the API handler, I would recommend simply suppressing the warning.

**Comment by SirLouen** [comment]
I only need a way to statically call the classes that are using those methods. 

I think the problem with all "Intellisense"-like plugins is that they need hard coded declarations for documentations purposes.
Since you are dynamically creating both Classes, the plugin doesn't know where those functions come from. But they can be statically called. The problem is that I don't know exactly which classes are being called without reviewing the whole code

**Comment by YahnisElsts** [comment]
What do you mean by "statically call the classes"?

**Comment by SirLouen** [comment]
I think this is a common issue with Intelephense due to the lack of strong typing in PHP

https://stackoverflow.com/questions/65558294/abstract-factory-class-returning-an-interface-type-method-not-found

With "statically" I meant, explicitely calling the class in the code that is calling the method, without abstracting or inferring though the params. 

Since I can't neither ignore the error, it's a pain 😞

**Comment by YahnisElsts** [comment]
There is a way to configure the VCS update checker manually if you really have to. It's more work, but it is possible. You could do something like this:

```php
$myGitHubApi = new Puc_v4p10_Vcs_GitHubApi($repositoryUrl);
$myGitHubApi->enableReleaseAssets();

$updateChecker = new Puc_v4p10_Vcs_PluginUpdateChecker(
	$myGitHubApi,
	__FILE__,
	'my-plugin-slug'
);
```

In this case, `Puc_v4p10_Vcs_PluginUpdateChecker` is an update checker subclass that deals with updating plugins from a VCS. It's constructor takes a VCS API instance as the first argument.

**Comment by SirLouen** [comment]
Looks great this way.

In this case, since both $updateChecker and $myGitHubApi have the `setAuthentication` method available, to which one shall be adapted for the ReleaseAssets functionality?

**Comment by YahnisElsts** [comment]
The `setAuthentication()` method on the update checker just calls the `setAuthentication()` method on the API class. So it doesn't really matter which one you use - the result will be the same either way.

Personally, I'd probably use the one on `$myGitHubApi` because that's more direct.

**Comment by SirLouen** [comment]
I think this does the trick 😃

**Comment by SirLouen** [comment]
I think this does the trick 😃
