### ISSUE TITLE
Check for updates only in WordPress Dashboard (is admin)

### ISSUE THREAD

**Issue by masoudarvishi** [YahnisElsts/plugin-update-checker#441]
Hello. I use the following if is_admin . But the library load crashes! I want the update check to be done only in the WordPress dashboard. Do not affect Frontend.

if ( ! is_admin() ) {

require 'path/to/plugin-update-checker/plugin-update-checker.php';
$myUpdateChecker = Puc_v4_Factory::buildUpdateChecker(
	'http://example.com/path/to/details.json',
	__FILE__, //Full path to the main plugin file or functions.php.
	'unique-plugin-or-theme-slug'
);

}

**Comment by YahnisElsts** [comment]
You mentioned a crash. Is there an error message of some kind when that happens? Please post it here.

**Comment by masoudarvishi** [comment]
I do not receive an error. But the library is no longer loaded with this if is_admin.
I want to check the update only in the WordPress admin section. Can you write a condition for this?

**Comment by YahnisElsts** [comment]
If there is no error then what is the reason to suspect that there was a crash?

As for the library no longer being loaded in the admin section, that's probably because the code you posted uses a `! is_admin()` condition. This means the code will only run when it's **not** in the admin panel. If you want the opposite, try removing the `!`.

**Comment by masoudarvishi** [comment]
thanks a lot. The problem was fixed.
