### ISSUE TITLE
Update failed: Download failed. Not Found

### ISSUE THREAD

**Issue by Proloy-Bhaduri** [YahnisElsts/plugin-update-checker#473]
I am passing valid downloadable zip file inside the json file and I'm able to download that  opening  the download_url in new browser tab .
I can see the new version available notice but when clicking on update now link  getting this error
**Update failed: Download failed. Not Found**

**Comment by YahnisElsts** [comment]
Here are some ideas:

- Do you have access to request logs on the update server? If so, check if the download request shows up in those logs and if it has the expected URL and status. This will help determine if the request reaches the server or if it encounters some kind of a problem along the way.
- You could try logging all HTTP requests sent by WordPress and plugins to see the full response that WordPress gets when it tries to download the update. Personally, I've done this before by using the [Core Control](https://wordpress.org/plugins/core-control/) plugin, but it has not been updated in a long time. Here's a more recent option: [Log HTTP Requests](https://wordpress.org/plugins/log-http-requests/). 
- Could it be that something on the WordPress site blocks outgoing HTTP requests? For example, if the site has a strict firewall, you may need to whitelist the update server.
- Similarly, does the update server have anything that could block specific requests? For example, maybe requests sent by WordPress could look like automated traffic (because that's basically what it is), and something is trying to block all bots.

**Comment by Proloy-Bhaduri** [comment]
Thank you very much for your quick and effective reply .
