### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by Zaeem6100** [YahnisElsts/plugin-update-checker#515]
I am using the GitHub integrations to update the theme. it works locally fine but with WP-ENGINE hosting and on multisite it wont works

**Comment by YahnisElsts** [comment]
Could you elaborate on "not working"? For example, does it mean that you're getting an error of some kind, or are update notifications not showing up, or do updates show up but you can't install them for some reason? 

Also, have you tried looking at the PUC debug information in the [Debug Bar](https://wordpress.org/plugins/debug-bar/)? Does everything look fine there?

**Comment by Zaeem6100** [comment]
In the child site with PUC, it shows that there is an update available 
![image](https://user-images.githubusercontent.com/32678310/210735513-870ae72b-948e-4eee-b2fb-3c3d966a0d26.png)

but in the Network admin site it don't show the PUC as well as update

**Comment by YahnisElsts** [comment]
Due to technical limitations, the update checker can only display an update when the update checker's code is running. If that code is part of a theme, it will only run in the network admin if that theme is active on the main site. Is it active on the main site?

If you can't/don't want to activate the theme on the main site, you'll need to find another way to run the update checker on the main site. For example, you could put that code in a small companion plugin, and activate only that plugin on the main site.

**Comment by Zaeem6100** [comment]
Done
