### ISSUE TITLE
Why does the zip file have to be different from what a standard plugin zip file should be according to Wordpress standards?

### ISSUE THREAD

**Issue by risharde** [YahnisElsts/plugin-update-checker#582]
As the title says, why does this have to be so?

**Comment by YahnisElsts** [comment]
Could you elaborate? In what way does it have to be different?

**Comment by risharde** [comment]
Hi Yahnis, sure, so I think according to the WordPress site, a plugin zip
does not have to have a subdirectory and then the files.

But this plugin updater seems to require this structure

**Comment by risharde** [comment]
I just realized the documentation on wordpress actually has the structure
you have which is to include the plugin name, maybe I missed that

**Comment by YahnisElsts** [comment]
I started writing a response before this was closed, and I'll post it anyway in case it helps clarify some things.

- As far as I know, all the plugins hosted on WordPress.org do have that structure[^1]. 
- It might not be explicitly called out in the documentation because WordPress.org automatically generates plugin ZIP files; it's not something you have to worry about there.
- WordPress core assumes that an update ZIP will contain a single subdirectory when installing an update[^2], and will install the update incorrectly if it doesn't.
- The current version of PUC includes a workaround for handling updates where the files are *not* in a subdirectory, but I still wouldn't recommend using that structure.

[^1]: With the possible exception of plugins that consist of a single .php file, but that's a special case and I haven't checked how WP core handles them now.
[^2]: But it's been a while since I've checked.
