### ISSUE TITLE
Timing out issues with Gitlab

### ISSUE THREAD

**Issue by Failcookie** [YahnisElsts/plugin-update-checker#92]
I am having some random issues grabbing theme updates from Gitlab. So far, I am 2/10 with successful updates. 6/10 timed out, but imports the theme. The rest will break the theme folder and not fully import.

I'm not sure what logs I can provide, but let me know and I will gladly provide some! Working well with Bitbucket.

**Comment by YahnisElsts** [comment]
Take a look at the PHP error log. Are there any messages from around the time when the update(s) failed?

**Comment by Failcookie** [comment]
Sorry for the delay on this! I went through my logs and didn't see any errors related to the plugin, so I am not sure if it was even capturing any errors. We switched over the repository to our Bitbucket account (Gitlab was temporary), so I haven't been proactive in searching for issues again. Working great on the Bitbucket side though!

**Comment by YahnisElsts** [comment]
The errors (if there are any) might not mention the plugin because the actual update installation is performed by WP core, not the update checker.

In any case, since you're no longer using GitLab for updates and nobody else has reported problems like that, it's probably not worthwhile to pursue the issue at this time. If you run into the same problem again in the future, feel free to reopen this.
